FROM node:alpine AS builder
WORKDIR /app
COPY . .
RUN npm install && npm run build

# nginx state for serving content
FROM nginx:alpine

COPY infra/default.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/build/ .
ENTRYPOINT ["nginx", "-g", "daemon off;"]