version: '3.4'

services:

  app:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ../
      dockerfile: infra/Dockerfile
    volumes:
      - /app/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000

  prod:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ../
      dockerfile: infra/Dockerfile.prod
    expose:
      - 3000
    ports:
      - 3000:3000

  wiremock:
    image: rodolpheche/wiremock
    container_name: wiremock
    volumes:
      - ./ __files:/home/wiremock/__ files
      - ./mappings:/home/wiremock/mappings
    ports:
      - 8080:8080
    command:
      - "--enable-stub-cors"